name: learn-github-actions

on:
 push:
  branches: [development]
 workflow_call:
  
jobs:
  learn-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: | 
               npm install
               npm run test
      - run: npm run coverage
    outputs:
         conclusion: success
      
  #merge:
    #runs-on: ubuntu-latest
    #needs: [learn-test]
    #steps:
      #- uses: actions/checkout@main
      #- name: Merge development -> main
        #uses: devmasx/merge-branch@v1.4.0
        #with:
          #type: now
          #from_branch: development
          #target_branch: main
          #github_token: ${{ github.token }}

    
    
