# This is a basic workflow to help you get started with Actions

name: sample CI pipeline

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
  
  on-success:
    runs-on: ubuntu-latest
    needs: call-build-test
    #if: ${{ needs.call-build-test.outputs.conclusion == 'success' }}
    
    steps:
      - run: echo ${{needs.call-build-test.outputs.conclusion}}
