# This is a basic workflow to help you get started with Actions

name: sample CI pipeline

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
  
  on-success:
    runs-on: ubuntu-latest
    if: ${{ needs.call-build-test.result == 'success' }}
    needs: call-build-test
    steps:
      - uses: actions/checkout@main
      - name: upload to s3
        uses: jakejarvis/s3-sync-action@master
        with:
         args: --acl public-read --follow-symlinks --delete
        env:
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1  
