# This is a basic workflow to help you get started with Actions

name: sample CI pipeline

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
  
  on-success:
    runs-on: ubuntu-latest
    if: ${{ needs.call-build-test.result == 'success' }}
    needs: call-build-test
    steps:
      - run: echo ${{ needs.call-build-test.result }}
