# This is a basic workflow to help you get started with Actions

name: sample CI pipeline

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:
  call-build-test:
    uses: ./.github/workflows/build-test.yml
  
  on-success:
    runs-on: ubuntu-latest
    if: ${{ needs.call-build-test.result == 'success' }}
    needs: call-build-test
    steps:
      - uses: actions/checkout@main
      - name: Merge development -> main
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: development
          target_branch: master
          github_token: ${{ github.token }}
